server:
  port: 8001
spring:
  application:
    name: cloud-provider-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.wyz.springcloud.entity
  mapper-locations: classpath:mapper/*.xml

